version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust #Nunca faça isso, estou fazendo porque é um teste
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
